import { useState, useCallback, useMemo } from 'react';
import { GitBranch, Upload, Copy, ExternalLink, Loader2, Check } from 'lucide-react';
import toast from 'react-hot-toast';
import { useStore } from '../../store';
import { commitTestAndOpenPR } from '../../utils/github';

interface CommitPanelProps {
  testCode: string;
  testFileName: string;
  prTitle: string;
  ticketId: string | null;
  prNumber: number;
}

export default function CommitPanel({
  testCode,
  testFileName,
  prTitle,
  ticketId,
  prNumber,
}: CommitPanelProps) {
  const config = useStore((s) => s.config);
  const [committing, setCommitting] = useState(false);
  const [prUrl, setPrUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const identifier = ticketId || `PR-${prNumber}`;
  const branchName = useMemo(
    () =>
      `test/${identifier.toLowerCase().replace(/[^a-z0-9-]/g, '-')}-e2e`,
    [identifier],
  );

  const targetConfigured =
    !!config.targetRepo.owner && !!config.targetRepo.name && !!config.githubToken;

  const handleCommit = useCallback(async () => {
    if (!targetConfigured || committing) return;
    setCommitting(true);

    try {
      const url = await commitTestAndOpenPR(
        config.githubToken,
        config.targetRepo.owner,
        config.targetRepo.name,
        branchName,
        testFileName,
        testCode,
        `test: add E2E for ${identifier} - ${prTitle}`,
        [
          `## Auto-generated E2E Test`,
          '',
          `Generated by PR-Test-Agent from ${identifier}.`,
          '',
          `- Source PR: #${prNumber}`,
          `- Test file: \`${testFileName}\``,
        ].join('\n'),
        `test: add E2E test for ${identifier}`,
      );

      setPrUrl(url);
      toast.success('PR created successfully');
    } catch (err: any) {
      toast.error(err.message || 'Failed to create PR');
    } finally {
      setCommitting(false);
    }
  }, [
    targetConfigured,
    committing,
    config,
    branchName,
    testFileName,
    testCode,
    identifier,
    prTitle,
    prNumber,
  ]);

  const handleCopyCode = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(testCode);
      setCopied(true);
      toast.success('Test code copied');
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error('Failed to copy');
    }
  }, [testCode]);

  return (
    <div className="bg-surface-secondary border border-border-default rounded-lg p-4 space-y-4">
      <h3 className="text-[13px] font-semibold text-content-primary">
        Commit & Open PR
      </h3>

      {/* Target repo info */}
      <div className="space-y-2">
        <div className="flex items-center gap-2 text-[12px]">
          <span className="text-content-tertiary w-20">Target repo:</span>
          {targetConfigured ? (
            <span className="font-mono text-content-primary">
              {config.targetRepo.owner}/{config.targetRepo.name}
            </span>
          ) : (
            <span className="text-warning">Not configured in Config</span>
          )}
        </div>
        <div className="flex items-center gap-2 text-[12px]">
          <span className="text-content-tertiary w-20">Branch:</span>
          <span className="font-mono text-content-primary flex items-center gap-1.5">
            <GitBranch className="w-3.5 h-3.5 text-accent" />
            {branchName}
          </span>
        </div>
        <div className="flex items-center gap-2 text-[12px]">
          <span className="text-content-tertiary w-20">File path:</span>
          <span className="font-mono text-content-secondary truncate">
            {testFileName}
          </span>
        </div>
      </div>

      {/* Actions */}
      <div className="flex items-center gap-2 pt-1">
        <button
          onClick={handleCommit}
          disabled={!targetConfigured || committing || !!prUrl}
          className={`
            flex items-center gap-2 px-4 py-2 rounded-md text-[13px] font-medium transition-colors
            ${
              targetConfigured && !committing && !prUrl
                ? 'bg-accent text-white hover:bg-accent-hover'
                : 'bg-surface-tertiary text-content-tertiary cursor-not-allowed'
            }
          `}
          aria-label="Commit and open pull request"
        >
          {committing ? (
            <>
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
              Creating PR...
            </>
          ) : prUrl ? (
            <>
              <Check className="w-3.5 h-3.5 text-success" />
              PR Created
            </>
          ) : (
            <>
              <Upload className="w-3.5 h-3.5" />
              Commit & Open PR
            </>
          )}
        </button>

        <button
          onClick={handleCopyCode}
          className="flex items-center gap-1.5 px-3 py-2 rounded-md text-[13px] font-medium
            bg-surface-tertiary text-content-secondary hover:text-content-primary transition-colors"
          aria-label="Copy test code"
        >
          {copied ? (
            <Check className="w-3.5 h-3.5 text-success" />
          ) : (
            <Copy className="w-3.5 h-3.5" />
          )}
          {copied ? 'Copied' : 'Copy Code'}
        </button>
      </div>

      {/* Created PR link */}
      {prUrl && (
        <a
          href={prUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1.5 text-[12px] text-accent hover:text-accent-hover transition-colors"
        >
          <ExternalLink className="w-3.5 h-3.5" />
          View Pull Request
        </a>
      )}
    </div>
  );
}
